### ISSUE TITLE
Can't install gem on a build agent behind firewall

### ISSUE THREAD

**Issue by mgrebenets** [ashfurrow/danger-ruby-swiftlint#106]
Hi

In my case I _can_ install Ruby gems on CI, we have a rubygems.org mirror setup via Artifactory.
But I _cannot_ install native extensions like for this particular gem, because it tries to install native extension, which involves downloading SwiftLint from GitHub: 'https://github.com/realm/SwiftLint'.
This is where it fails for me.
This is unfortunate, but this is what we have to deal with.

In any case, we plan to use SwiftLint Danger plugin combined with `swiftlint.binary_path`, so as a matter of fact we don't need the pre-packaged SwiftLint to be installed at all.

Is there a way to install the gem without native extensions?
Could it be possible to install just the Ruby part of the gem, but not the bundled SwiftLint executable?

E.g. in a way how `SWIFTLINT_VERSION` is exposed, can there be another env var that skips the whole SwiftLint installation steps completely? E.g. `SKIP_SWIFTLINT_INSTALL`?

**Comment by ashfurrow** [comment]
Should be fixed by #107, released as 0.17.2. Thanks!
