### ISSUE TITLE
Use --use-script-input-files instead of running on each file

### ISSUE THREAD

**Issue by mbogh** [ashfurrow/danger-ruby-swiftlint#111]
Hi,

First of all, thanks for a nice addition to Danger 🥇 

We recently ran into the `invalid byte sequence in UTF-8` error which happens under certain circumstances within `ruby-git`. So I changed our use of this plugin to pass all swift files into `swiftlint.lint_files`.
This however resulted a runtime of 19 minutes for linting ~1300 swift files on our CI vs roughly 1 minute  using `swiftlint` in the terminal.

So I looked into the source and in `danger_plugin.rb` [run_swiftlint](https://github.com/ashfurrow/danger-ruby-swiftlint/blob/8c3fd5943080eeee82b15c99bd495ed988fb557a/lib/danger_plugin.rb#L126) is run on each file individually. 
My guess is that this is why the runtime goes from 1 minute to 19 minutes.

Would you be interested in a pull request that uses the `--use-script-input-files` like it is done in the [fastlane::swiftlint](https://github.com/fastlane/fastlane/blob/9f164d924c8fbd15f7ac257c95b01ea93d2067d5/fastlane/lib/fastlane/actions/swiftlint.rb#L22) plugin?

Cheers
Morten

**Comment by ashfurrow** [comment]
@mbogh awesome, thank you!
