### ISSUE TITLE
Filter out non-inline violations?

### ISSUE THREAD

**Issue by daniel-beard** [ashfurrow/danger-ruby-swiftlint#125]
Wondering if there is a way to filter out all violations that don't occur in the diff. 
E.g. If I have `inline_mode: true`, I'd like to *not* add any violations to the markdown summary and strip out or ignore everything that doesn't occur on a changed line in the diff.

Is there anything for this currently? Otherwise I don't mind contributing this behavior.

**Comment by ashfurrow** [comment]
Oh, so it'd be like "this file is changed, and it has violations, but those violations aren't in the scope of the file's diff, so ignore them"? That sounds pretty reasonable! I don't think we have support for it, but it'd certainly be welcome. Ideally, a PR adding this feature would include some unit tests to make sure we can maintain it longterm. Let me know what I can clarify and if I can give additional context.

**Comment by daniel-beard** [comment]
Closing, this is implemented
