### ISSUE TITLE
Undefined `swiftlint`?

### ISSUE THREAD

**Issue by gdoublev** [ashfurrow/danger-ruby-swiftlint#138]
To preface this, I work behind a corporate firewall/proxy, and unfortunately _some_ GitHub repositories whose release artifacts are hosted on AWS CDN are completely blocked. [SwiftLint](https://github.com/realm/SwiftLint/) is one of those repos.

All that is to say that the install process for this gem was not easy or fun (usually never is for me, regardless of the dependency, not your fault).

So this is basically what I did:
```bash
# clone SwiftLint at the version that we need (0.31.0)
git clone --branch 0.31.0 https://github.com/realm/SwiftLint.git
cd SwiftLint

# build and install SwiftLint
git submodule update --init --recursive; make install

# verify SwiftLint installed:
which swiftlint # should output: "/usr/local/bin/swiftlint"
swiftlint version # should output "0.31.0"

# tell the installer for this gem to skip installing SwiftLint because we did it ourselves already
export DANGER_SKIP_SWIFTLINT_INSTALL="YES"
gem install danger-swiftlint -v 0.21.1

# after installation, we need to symlink SwiftLint into this gem's bin path
cd ~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/danger-swiftlint-0.21.1/ext/swiftlint/
mkdir bin;cd bin
ln -s /usr/local/bin/swiftlint $PWD/swiftlint
```

I got `~/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/danger-swiftlint-0.21.1/ext/swiftlint/bin/` as the install path that your [Rakefile](https://github.com/ashfurrow/danger-ruby-swiftlint/blob/master/ext/swiftlint/Rakefile) was attempting to install SwiftLint at.

Anyways, immediately after doing this (a couple days ago), everything worked, I was able to run `danger pr` locally and test lint a PR without issue. Even worked when running the Jenkins job against the PR. I don't believe anything has changed in the last couple days, but as of yesterday our PR's are now failing the linting stage with the following error:
```
[12:21:34]: Exit status of command 'bundle exec danger --verbose --danger_id=danger_linting --dangerfile=/Users/<jenkins-username>/jenkins-agent/workspace/<job-name-directory>/.build/Dangerfile --fail-on-errors=true' was 1 instead of 0.
You used `puts` in your Dangerfile. To print out text to GitHub use `message` instead
bundler: failed to load command: danger (/Users/<jenkins-username>/.rbenv/versions/2.6.3/bin/danger)
Danger::DSLError: [31m
[!] Invalid `Dangerfile` file: undefined local variable or method `swiftlint' for #<Danger::Dangerfile:0x00007f92a910f728>[0m
 #  from /Users/<jenkins-username>/jenkins-agent/workspace/<job-name-directory>/.build/Dangerfile:4
 #  -------------------------------------------
 #  if !(github.pr_labels.include? "skip-linting")
 >    swiftlint.config_file = '.build/swiftlint.yml'
 #    swiftlint.binary_path = '/usr/local/bin/swiftlint'
 #  -------------------------------------------

  /Users/<jenkins-username>/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/danger-6.1.0/lib/danger/danger_core/dangerfile.rb:70:in `method_missing'
  /Users/<jenkins-username>/jenkins-agent/workspace/<job-name-directory>/.build/Dangerfile:4:in `eval_file'
  /Users/<jenkins-username>/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/danger-6.1.0/lib/danger/danger_core/dangerfile.rb:297:in `eval'
  /Users/<jenkins-username>/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/danger-6.1.0/lib/danger/danger_core/dangerfile.rb:297:in `eval_file'
  /Users/<jenkins-username>/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/danger-6.1.0/lib/danger/danger_core/dangerfile.rb:200:in `block in parse'
  /Users/<jenkins-username>/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/danger-6.1.0/lib/danger/danger_core/dangerfile.rb:197:in `instance_eval'
  /Users/<jenkins-username>/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/danger-6.1.0/lib/danger/danger_core/dangerfile.rb:197:in `parse'
  /Users/<jenkins-username>/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/danger-6.1.0/lib/danger/danger_core/dangerfile.rb:273:in `run'
  /Users/<jenkins-username>/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/danger-6.1.0/lib/danger/danger_core/executor.rb:29:in `run'
  /Users/<jenkins-username>/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/danger-6.1.0/lib/danger/commands/runner.rb:72:in `run'
  /Users/<jenkins-username>/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
  /Users/<jenkins-username>/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/danger-6.1.0/bin/danger:5:in `<top (required)>'
  /Users/<jenkins-username>/.rbenv/versions/2.6.3/bin/danger:23:in `load'
  /Users/<jenkins-username>/.rbenv/versions/2.6.3/bin/danger:23:in `<top (required)>'
```

This is our Dangerfile:
```ruby
if !(github.pr_labels.include? "skip-linting")
  swiftlint.config_file = '.build/swiftlint.yml'
  swiftlint.binary_path = '/usr/local/bin/swiftlint'
  swiftlint.lint_files fail_on_error: true
  puts "Completed Linting Stage!"
else
  warn "You skipped linting."
end
```

Any ideas what could be wrong? I'm kinda stumped at this point. I assumed maybe it had something to do with Ruby or Danger itself not knowing what "swiftlint" is, so I tried to add a symlink to it in `~/.rbenv/shims` but that cleaned itself up and removed it the next time Terminal was opened (or the next time RBENV was initialized).

**Comment by ashfurrow** [comment]
Hey! Thanks for opening the issue – sorry for the delay in responding (holidays).

It doesn't look like it's SwiftLint's installation that is the issue. Ruby is complaining that there is no `swiftlint` variable, but that _should_ be loaded as a result of having the `danger-ruby-swiftlint` in your Gemfile. The problem is that Danger isn't finding the `danger-ruby-swiftlint` plugin, not that it can't find the SwiftLint executable.

I've read and re-read the console output you've provided and it all looks good. I've [looked through the Danger issues](https://github.com/danger/danger/issues) and couldn't find anything relevant. You said it was working, and then stopped? Did you update Ruby or Danger versions in the interim?

**Comment by gdoublev** [comment]
I have not. Still using:
- ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin17]
- danger (6.1.0)
- danger-swiftlint (0.21.1)
- fastlane 2.137.0
- swiftlint 0.31.0

When I run `danger --version`, get some nice deprecation output before the version too 😝 
```bash
danger --version
NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
Faraday::Error::ClientError.inherited called from /Users/<jenkins-username>/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.
6.1.0
```

**Comment by ashfurrow** [comment]
Okay thanks, and thanks for the info. Those all look good.

Taking a look again, it could be the way that the `danger-swiftlint` gem is installed. You have this line in the CI config:

```sh
gem install danger-swiftlint -v 0.21.1
```

And this installs `danger-swiftlint` in the global gems. But later, you invoke `danger` through Bundler:

```sh
bundle exec danger ...
```

So I'm wondering if that could be the source of the problem? I think Danger uses the `Gemfile` to load Danger plugins, so being installed as a global gem might not be enough to actually load the plugin (which would cause the error we're seeing). I took a look [through Danger's plugin-loading code](https://github.com/danger/danger/tree/master/lib/danger/plugin_support) but didn't see any smoking guns.

Here's what I'd try next: you can either install Danger globally, or (what I'd recommend) is moving the `danger-swiftlint` installation out of `gem install` and into your `Gemfile`. Let me know what I can clarify.

**Comment by gdoublev** [comment]
Honestly, still a bit new to some of the CI stuff, so I genuinely didn't know there was a difference in how gems were installed (via `gem install danger-swiftlint -v 0.21.1` vs. `bundle install` using a cloned repo's Gemfile). I'll uninstall everything and see if installing them all one specific way helps.

It's a tad bit confusing when I go to list gems and they're saying "LOCAL" even though you're right, I'm pretty sure I installed them globally on the system via that `gem install` command.

```bash
$ gem list -e danger -d

*** LOCAL GEMS ***

danger (6.1.0)
    Authors: Orta Therox, Juanito Fatas
    Homepage: https://github.com/danger/danger
    License: MIT
    Installed at: /Users/<jenkins-username>/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0

    Like Unit Tests, but for your Team Culture.

$ gem list -e danger-swiftlint -d

*** LOCAL GEMS ***

danger-swiftlint (0.21.1)
    Authors: Ash Furrow, David Grandinetti, Orta Therox, Thiago Felix,
    Giovanni Lodi
    Homepage: https://github.com/ashfurrow/danger-ruby-swiftlint
    License: MIT
    Installed at: /Users/<jenkins-username>/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0

    A Danger plugin for linting Swift with SwiftLint.
```

I'm also confused where the heck that "2.6.0" number comes from, because if I were to do a `gem -v` it spits out **3.0.3**, not **2.6.0**. 🤷‍♂

**Comment by gdoublev** [comment]
You're a damn genius, @ashfurrow ! Can't thank you enough for the assistance and I apologize for my rookie mistake.

```bash
$ gem list -a danger

*** LOCAL GEMS ***

danger (6.1.0)
danger-swiftlint (0.21.1)
$ gem uninstall -a danger-swiftlint
Remove executables:
	danger-swiftlint

in addition to the gem? [Yn]  Y
Removing danger-swiftlint
Successfully uninstalled danger-swiftlint-0.21.1
$ gem uninstall -a danger
Remove executables:
	danger

in addition to the gem? [Yn]  Y
Removing danger
Successfully uninstalled danger-6.1.0

$ bundle install
Warning: the running version of Bundler (1.17.2) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
... removed irrelevant spam
Fetching danger 6.1.0
Installing danger 6.1.0
Fetching danger-swiftlint 0.21.1
Installing danger-swiftlint 0.21.1 with native extensions
... more irrelevant spam removal
Bundle complete! 12 Gemfile dependencies, 126 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.


$ bundle exec danger pr <github-enterprise-url> --dangerfile=.build/Dangerfile --danger_id="danger_linting" --verbose --fail-on-errors=true
Running your Dangerfile against this PR - <github-enterprise-url>

You used `puts` in your Dangerfile. To print out text to GitHub use `message` instead
Completed Linting Stage!
Results:

Errors:
- [ ] Failed due to SwiftLint errors

Markdown:
### SwiftLint found issues

#### Warnings

File | Line | Reason |
| --- | ----- | ----- |
SomeRandomViewController.swift | 121 | Colons should be next to the identifier when specifying a type and next to the key in dictionary literals. (colon)
```

That was run locally, going to test it through Jenkins now, but got excited and wanted to post this small victory here first.

**Comment by gdoublev** [comment]
Reporting back in, successfully running against PR's using Jenkins. Thanks again so much for all of your help with this, you are the best! 👍

**Comment by ashfurrow** [comment]
@gdoublev Awesome! So glad that worked 🎉 Absolutely no need to apologize, either. Could make a good blog post, if you're keen!
