### ISSUE TITLE
Inline Swiftlint comments are crossed out

### ISSUE THREAD

**Issue by austinwright** [ashfurrow/danger-ruby-swiftlint#145]
Hi, I'm seeing this on my inline swiftlint errors and warnings after a successful CI run with danger and danger-ruby-swiftlint. The plain Danger warning does not appear with strikethrough. It happens on PR open and re-open. (Note I have been using the same test branch for debugging the CI workflow and there are several closed PRs - could this be the issue?).

Versions:
danger: `danger (6.3.1)`
danger-swiftlint: `danger-swiftlint (0.24.2)`

Screenshots:

Inline SwiftLint violation:
<img width="571" alt="Screen Shot 2020-03-11 at 4 52 03 PM" src="https://user-images.githubusercontent.com/1952159/76464099-13c60480-63bb-11ea-9d17-8822d8ecda8b.png">

Normal Danger comment:
<img width="664" alt="Screen Shot 2020-03-11 at 4 56 40 PM" src="https://user-images.githubusercontent.com/1952159/76464095-10cb1400-63bb-11ea-9354-cfb818f8b912.png">

**Comment by ashfurrow** [comment]
Danger normally edits/deletes comments on subsequent runs, so the comments are always up-to-date. I would bet that strikethrough is a feature of Danger's that is only used on inline comments. I'm not sure – I don't use the inline comment feature.

**Comment by austinwright** [comment]
Hmm, looks like you're right: https://github.com/danger/danger/issues/1189

Though when browsing the diff between the latest release and 6.2.0 nothing stuck out as being the root cause of this odd behavior 🤔 . I will comment on that issue to try and gain some additional traction.

**Comment by ashfurrow** [comment]
I'll note that the creator of Danger tends not to use inline comments either, so it might be worth seeking out developers who implemented it and asking for advice.
