### ISSUE TITLE
Lint error for "masterCard" inclusive_language

### ISSUE THREAD

**Issue by apps4everyone** [ashfurrow/danger-ruby-swiftlint#165]
On local Xcode Setup (https://github.com/realm/SwiftLint 0.43.1) the `inclusive_language` has `masterCard` in the `allowance list`.

But on CI I get:
`Declaration masterCard contains the term "master" which is not considered inclusive.`

for:
`case masterCard = "MASTERCARD"`

**Comment by apps4everyone** [comment]
`.swiftlint.yml`:
```
inclusive_language:
  override_allowed_terms: ["mastercard", "MASTERCARD"]
```

**Comment by mokagio** [comment]
I'd say this is safe to close. I haven't searched for those usages, but being in the `override_allowed_terms` list, they clearly represent an intentional compromise.

**Comment by apps4everyone** [comment]
Hey, thx for the fast reply. Tested with disabling:
`- inclusive_language`
and the error is gone on CI.

What version of `https://github.com/realm/SwiftLint` is used as binary or what is the default path for `swiftlint.binary_path`?

**Comment by apps4everyone** [comment]
Looks like the problem is the outdated version: `0.41.0` here:
https://github.com/ashfurrow/danger-ruby-swiftlint/blob/77360835f4a6d5bb87678ee5865a0c0255a1361a/lib/version.rb#L5
and Mastercard was fixed with `0.42.0` see here:
https://github.com/realm/SwiftLint/blob/master/CHANGELOG.md#0420-he-chutes-he-scores

Latest version: https://github.com/realm/SwiftLint/releases/tag/0.43.1

**Comment by apps4everyone** [comment]
best would be to add the functionality to specify the version e.g.:
swiftlint.swift_lint_version = '0.43.1'
and use by default the latest?

**Comment by ashfurrow** [comment]
You can set the `SWIFTLINT_VERSION` environment variable to whatever you want, and [danger-swiftlint will install that version](https://github.com/ashfurrow/danger-ruby-swiftlint/blob/77360835f4a6d5bb87678ee5865a0c0255a1361a/ext/swiftlint/Rakefile#L11). The version we specify in `version.rb` is a fallback if you don't specific one with the `SWIFTLINT_VERSION` env var.

**Comment by mokagio** [comment]
@apps4everyone thank you for your research work 😄 

Sounds like you've done most of the hard work already, how would you feel about opening a PR that updates the fallback version to the latest stable SwiftLint to see if everything works fine with that?
