### ISSUE TITLE
CI isn't passing

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/danger-ruby-swiftlint#171]
Travis changed something and our builds aren't running: https://travis-ci.org/github/ashfurrow/danger-ruby-swiftlint/builds Need to either migrate to `travis-ci.com` or another CI provider.

**Comment by EgorVeremeychikEffectiveSoft** [comment]
Hello, @ashfurrow 
Is there any updates?

**Comment by dirtyhabits97** [comment]
It seems pretty straightforward and shouldn't take more than 5 minutes according to [this guide ](https://docs.travis-ci.com/user/migrate/open-source-repository-migration#migrating-a-repository). It also looks like only repo owners can do the migration.

**Comment by ashfurrow** [comment]
Okay, progress! The builds are _running_ but they're not _passing_. Example failure: https://app.travis-ci.com/github/ashfurrow/danger-ruby-swiftlint/builds/237659622 I'll try to take a look later. Seems related to #169 /cc @rogerluan. I'll try to take a look later.

**Comment by rogerluan** [comment]
Thanks for the friendly tag @ashfurrow ! 💪 
@dirtyhabits97 let me know if you have the spare time to check those failures, since you implemented those unit tests 🙏 I'd highly appreciate the help! 🙇
