### ISSUE TITLE
Question: How do I make it use the globally installed swiftlint ?

### ISSUE THREAD

**Issue by hlung** [ashfurrow/danger-ruby-swiftlint#189]
I know there is `swiftlint.binary_path = '/path/to/swiftlint'`, but is there a way to do this without having to specify the path? Reason being we may need to change how we install swiftlint in future, and its binary path may change. This way we don't need to keep updating this path.

**Comment by ashfurrow** [comment]
You could run `which swiftlint` to get the path and set `binary_path` that way.

**Comment by hlung** [comment]
@ashfurrow oh can I use `swiftlint.binary_path = which swiftlint` ?

**Comment by hlung** [comment]
Found it. 
```
`which swiftlint`.strip
```
Need strip because the output of which has `\n` at the end, which will mess up danger.
