### ISSUE TITLE
Update to SwiftLint 0.50.3

### ISSUE THREAD

**Issue by FabienLydoire** [ashfurrow/danger-ruby-swiftlint#191]
Hello Danger-Swiftlint Team :) 

If you had time to update to SwiftLint 0.50.3 (released this Dec 9, 2022) it would be great !
I see the 0.50.0 update here #188 
Is it easier if I propose a PR, or you can do it yourself ?

**Comment by ashfurrow** [comment]
A PR would be welcome, thank you. I honestly haven’t had the time / energy to invest in this project lately.

**Comment by FabienLydoire** [comment]
Thanks for the quick reply Ash. Will do !

**Comment by FabienLydoire** [comment]
Done #192
