### ISSUE TITLE
Remove native extensions

### ISSUE THREAD

**Issue by manicmaniac** [ashfurrow/danger-ruby-swiftlint#203]
When running `bundle install`, it says `danger-swiftlint` has a native extension but actually it does not.

```
$ cat Gemfile
source "https://rubygems.org"
gem "danger-swiftlint"
$ bundle install
...
Fetching danger-swiftlint 0.36.1
Installing danger-swiftlint 0.36.1 with native extensions
...
```

https://github.com/ashfurrow/danger-ruby-swiftlint/blob/16dbb9f23ff2688bc4b1ab185793f87a3121b4af/danger-swiftlint.gemspec#L20

**Comment by ashfurrow** [comment]
It does, though. It installs Swiftlint: 

https://github.com/ashfurrow/danger-ruby-swiftlint/blob/d11176448b698442255536228e392131e7855c53/ext/swiftlint/Rakefile
