### ISSUE TITLE
danger-swiftlint 0.11 seems to be broken

### ISSUE THREAD

**Issue by freak4pc** [ashfurrow/danger-ruby-swiftlint#74]
After updating to danger-swiftlint 0.11 my PRs seem to break with the following error:
![2017-11-12 15 54 14](https://user-images.githubusercontent.com/605076/32699633-c14baa8a-c7c1-11e7-9859-7753a30b6d93.jpg)

Rolling back to 0.10 resolves the issue so I assume this is a new bug introduced in latest release.

**Comment by thii** [comment]
Does 0.10.2 work for you? What version of SwiftLint are you using?

**Comment by ajfigueroa** [comment]
I'm also seeing the issue on 0.10.2
`[!] Invalid `Dangerfile` file: undefined method `positive?' for 0:Fixnum`

**Comment by ashfurrow** [comment]
Hmm, can you let me know what Ruby and Bundler versions you have? It would help to reproduce. Thanks!

**Comment by ajfigueroa** [comment]
Sure, my CI (Bitrise) was using Ruby v2.4.0 and Bundler was at v1.16.0
I ended up reverting the plugin back to `0.10.1` to get things working as normal so the issue seems to happen on v0.10.2+.

**Comment by freak4pc** [comment]
I'll have to check with buddybuild as its running (and failing) on their CI
:)

-- 
Shai Mishali

**Comment by ashfurrow** [comment]
Thanks for the follow-up. I'll try to take a look at this on Saturday/Sunday but time is really tight right now 😬  If anyone is available to lend a hand tracking down the source of the problem, I'd be very grateful 🙇

**Comment by ajfigueroa** [comment]
@ashfurrow No problem, happy to help. I've edited my above comment with the error log.

**Comment by freak4pc** [comment]
Uhm that's interesting @ajfigueroa 
`danger local` works fine for me 🤔 (otherwise this would be super-easy to fix with a git bisect)

Ruby: ruby 2.4.1p111
Bundler: 1.16.0

**Comment by freak4pc** [comment]
Rolled back with RVM to 2.4.0 so be on part with your configuration but couldn't get it to "fail" either. That's very very interesting :)

**Comment by RishabhTayal** [comment]
I am having the same issue.

**Comment by freak4pc** [comment]
I couldn't reproduce locally with `danger local` but this was still failing on my CI which is interesting. I'll try to dig further into this over the weekend but if anyone else has some time to take a crack at it that would be highly appreciated :)

**Comment by ashfurrow** [comment]
Thanks @freak4pc – any help would be appreciated. I'm afraid that I don't have a lot of availability to work on this right now.

**Comment by ashfurrow** [comment]
Okay, this was fixed by @thii and released as 0.12.1. Please let us know how it goes 👍

**Comment by freak4pc** [comment]
Great news !
