### ISSUE TITLE
Fail on error doesn't work as expected.

### ISSUE THREAD

**Issue by omirho** [ashfurrow/danger-ruby-swiftlint#89]
`fail_on_error` behavior should be to fail Danger, but instead it crashes danger with a cryptic message.
<img width="969" alt="screen shot 2018-02-21 at 9 15 50 pm" src="https://user-images.githubusercontent.com/2761158/36492458-35854d26-1753-11e8-866d-7464da7480fa.png">

This is due to using `raise` instead of Danger's `fail` method.

I came upon this issue when I removed `inline_mode` from my config.

After checking the history, I came upon [this](https://github.com/ashfurrow/danger-ruby-swiftlint/pull/61) PR which introduced the issue.

I'll be happy to raise a PR to fix this after receiving a 👍

**Comment by omirho** [comment]
Also, `inline_mode` fails Danger on errors irrespective of `fail_on_error` being true or not.
This should either be mentioned in the README or changed.
I think it should be changed though.

**Comment by ashfurrow** [comment]
Hmm! Great catch, thanks. A PR to fix this would be welcome 🙇 As for the `inline_mode`, I admit I've never used it. It sounds like a bug, would you care to open an issue with steps to reproduce? Thanks again!
